# Generated by Django 6.0.7 on 2026-07-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_medicine_description_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clinic.doctor'),
        ),
    ]
