# Generated by Django 6.0.7 on 2026-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_invoice_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='default_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default discount percentage (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='default_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax percentage (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='enable_appointment_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='invoice_prefix',
            field=models.CharField(default='INV-', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when medicine stock is below this number'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='next_invoice_number',
            field=models.IntegerField(default=1001),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='working_hours_from',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='working_hours_to',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='ClinicFlow Pro', max_length=255),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='currency',
            field=models.CharField(choices=[('$', 'USD - US Dollar ($)'), ('€', 'EUR - Euro (€)'), ('£', 'GBP - British Pound (£)'), ('EGP', 'EGP - Egyptian Pound'), ('SAR', 'SAR - Saudi Riyal'), ('AED', 'AED - UAE Dirham')], default='EGP', max_length=10),
        ),
    ]
