# Generated by Django 6.0.7 on 2026-07-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='smtp_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
